# Icon
favicon: /jeamn.png
# SEO
keywords: Hexo, javascript
# Header
page_background: http://ww1.sinaimg.cn/large/8b50d584gy1ffcpdjp9vtj211a0ou79p.jpg
page_menu_button: dark
post_background: http://callfiles.ueibo.com/hexo-theme-laughing/post_background.jpg
post_menu_button: light
title_plancehold: 随笔
author:
  head: http://ww1.sinaimg.cn/large/8b50d584gy1ffcq23v5puj20cg0chjsj.jpg
  signature: 罗斯柴尔德之密西西比拾棉者
  navication:
  - name: Github
    link: https://github.com/Jeamn
  - name: E-mail
    link: mailto:jeamnchan@gmail.com
# content
content_width: 950
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: https://github.com/Jeamn
  #- name: Weibo
   # icon: weibo
    #link: http://weibo.com/p/1005052337330564/home?from=page_100505&mod=TAB&is_all=1#place
  #- name: SegmentFault
   # icon: segmentfault
    #link: https://www.segmentfault.com/u/bon
#Duoshuo
duoshuo:
  enable: true
  siteName: jeamn
# Copyright
copyright:
  record: false
  hexo: false
  laughing: false